Lesson6
NtonBala/React-Blog pull request #12
Opened 2017-11-15 13:07 UTC by NtonBala

2017-11-17 08:36 UTC, index01d requested changes

2017-11-17 08:36 UTC, index01d commented on package.json
> +    "redux-devtools": "^3.4.0",
можно на будущее также посмотреть https://github.com/zalmoxisus/redux-devtools-extension ; работает немного производительнее (что ощутимо на большом приложении), дает те же преимущества.

2017-11-17 08:36 UTC, index01d commented on src/actions/Posts.js
> +//increment post likes
лайки нужно вынести в отдельный action-модуль и сделать только requestIncrementLike (ставится же всегда 1 лайк)

2017-11-17 08:36 UTC, index01d commented on src/actions/Posts.js
> +//increment post likes
результат выполнения одного action'a можно обработать в двух reducer'ах

2017-11-17 08:36 UTC, index01d commented on src/components/BlogPage.js
> +const BlogPage = ({blogItems, like, error, isRequesting}) => {
Этот промежуточный компонент больше не нужен, должен быть заменен на компонент без собственного состояния. Можно сделать отдельные redux-контейнеры для PieChart (PieChartContainer) и для списка записей BlogListContainer

2017-11-17 08:36 UTC, index01d commented on src/components/BlogPost.js
> +            like={() => like(blogItem._id)}
лучше сделать LikeContainer для кнопки лайка и не таскать функцию like по иерархии

2017-11-17 08:36 UTC, index01d commented on src/containers/PostContainer.js
> +    like: () => dispatch(incrementLikes(ownProps.params.post_id))
должно быть в LikeContainer'е

2017-11-17 08:36 UTC, index01d commented on src/containers/PageContainer.js
> +    like: flowRight(dispatch, incrementLikes)
должно быть одной функцией action-Creator'ом (incrementLike) и находиться в LikeContainer'е

2017-11-17 08:43 UTC, NtonBala commented on package.json
> +    "redux-devtools": "^3.4.0",
Круто) Я лазил в допы к 6 уроку, там очень много классной инфы. И когда лопатил ссылки на него наткнулся. Я уже даже юзал это расширение для хрома на тестовом одном.

2017-11-17 08:44 UTC, NtonBala commented on package.json
> +    "redux-devtools": "^3.4.0",
Теперь буду знать его преимущество)

2017-11-20 14:32 UTC, NtonBala commented on src/components/BlogPage.js
> +const BlogPage = ({blogItems, like, error, isRequesting}) => {
Тут непонятно с полем isFetching в сторе. Оно ведь относиться и к PieChart, и к BlogList. То, что мне сейчас в голову приходит, это что где-то дальше у нас будет App подписан на стор и он и будет обрабатывать и isFetching, и error. Я тогда поля эти поля isFetching & error пока вообще в компонентах обрабатывать не буду.

2017-11-21 10:09 UTC, closed without merging